# Generated by Django 3.0.8 on 2024-12-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(upload_to='song_file/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_img',
            field=models.FileField(upload_to='song_img/'),
        ),
    ]
