# Generated by Django 3.0.8 on 2024-12-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_auto_20241209_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='code',
        ),
    ]
